// +build mock

// Code generated by github.com/koron/mockgo; DO NOT EDIT.

package service

import "github.com/koron/todo-noif-mock/do"

// Repository is a mock of repository.Repository for test.
type Repository struct {
	Insert_Ps []*RepositoryInsert_P
	Insert_Rs []*RepositoryInsert_R
}

// RepositoryInsert_P packs input parameters of repository.Repository#Insert method.
type RepositoryInsert_P struct {
	Todo *do.Todo
}

// RepositoryInsert_R packs output parameters of repository.Repository#Insert method.
type RepositoryInsert_R struct {
	Out0 *do.Todo
	Out1 error
}

// Insert is mock of repository.Repository#Insert method.
func (_m *Repository) Insert(todo *do.Todo) (*do.Todo, error) {
	_m.Insert_Ps = append(_m.Insert_Ps, &RepositoryInsert_P{todo})
	var _r *RepositoryInsert_R
	_r, _m.Insert_Rs = _m.Insert_Rs[0], _m.Insert_Rs[1:]
	return _r.Out0, _r.Out1
}
